export const momentumSubstepDetails: Record<string, string[]> = {
  "1.1": [
    "Channel Strategy Architecture:",
    "When to use:",
    "Cold call vs cold email vs LinkedIn",
    "Inbound vs referral handling",
    "Channel sequencing strategy",
    "Example:",
    "Email first → call second",
    "Call first → email follow-up",
    "Event → LinkedIn → meeting conversion",
    "Channel-Specific Buyer Psychology:",
    "Buyer psychology by channel:",
    "Trust baseline",
    "Response expectation",
    "Attention window",
    "Risk perception",
    "Example:",
    "Cold call objection psychology ≠ inbound objection psychology",
    "Channel-Specific Messaging Frameworks:",
    "Messaging frameworks by channel:",
    "First-touch structure",
    "Hook frameworks",
    "Openers",
    "CTAs",
    "Follow-up variants",
    "Channel Economics:",
    "Response rates",
    "Conversion benchmarks",
    "Channel efficiency tradeoffs",
    "Hungry reps should know:",
    "Where effort compounds",
    "Where effort gets wasted",
    "Channel Failure Modes:",
    "Failure modes by channel:",
    "Cold: irrelevance",
    "Event: no follow-up",
    "Referral: assumed trust",
    "Inbound: lack of control",
    "Edge Cases:",
    "Prospect responds but vague",
    "Prospect asks for deck immediately",
    "Prospect pushes to junior instead",
    "Prospect says “circle back next quarter”"
  ],
  "1.2": [
    "Persona Taxonomy:",
    "Persona types:",
    "Economic buyer",
    "Functional buyer",
    "Technical evaluator",
    "User champion",
    "Blocker",
    "Entry Persona Selection Strategy:",
    "Who should be first contact?",
    "Depends on:",
    "Problem type",
    "Deal complexity",
    "Org structure",
    "Persona Incentive Mapping:",
    "Persona incentive mapping:",
    "What do they care about?",
    "What do they fear?",
    "What do they get rewarded for?",
    "Persona Mis-targeting Failure Modes:",
    "Examples:",
    "Selling strategic pain to low-level user",
    "Selling efficiency to executive who cares about risk",
    "Engaging influencer while ignoring blocker",
    "Multi-Threading at Contact Stage:",
    "When to single-thread",
    "When to multi-thread",
    "How not to create internal confusion",
    "Stakeholder Political Mapping:",
    "Advanced:",
    "Who can support?",
    "Who can sabotage?",
    "Hidden power centers"
  ],
  "1.3": [
    "Hypothesis Sources:",
    "Hypothesis sources:",
    "Industry patterns",
    "Trigger events",
    "Public signals",
    "Role patterns",
    "Problem Strength Testing:",
    "How to know if hypothesis is strong enough",
    "Questions:",
    "Pain or nuisance?",
    "Important or optional?",
    "Urgent or abstract?",
    "Problem Framing Techniques:",
    "Problem framing options:",
    "Cost framing",
    "Risk framing",
    "Opportunity framing",
    "Wrong-Hypothesis Recovery:",
    "What if you guessed wrong?",
    "Trigger-Based Timing:",
    "“Why now?”"
  ],
  "1.4": [
    "Message Anatomy:",
    "First-touch anatomy:",
    "Opener",
    "Relevance trigger",
    "Problem hook",
    "Curiosity gap",
    "Ask",
    "Opening Line Libraries:",
    "Cold-call openers",
    "Email openers",
    "Event openers",
    "Response Pattern Handling:",
    "Response handling examples:",
    "“Not interested”",
    "“Send details”",
    "“Already have a vendor”",
    "This becomes playbooks.",
    "Attention Capture Mechanics:",
    "Subject lines",
    "Pattern interrupts",
    "Short-form persuasion",
    "Tone Calibration:",
    "Direct vs consultative vs provocative"
  ],
  "1.5": [
    "Sequencing Architecture:",
    "Touch 1",
    "Touch 2",
    "Touch 3…",
    "Timing logic",
    "Follow-up Angle Rotation:",
    "Each follow-up must add:",
    "New insight",
    "New trigger",
    "New reason to respond",
    "Persistence vs Stop Rules:",
    "When to keep pushing",
    "When to walk away",
    "“No Response” Interpretation:",
    "Silence means different things.",
    "Re-engagement Plays:",
    "Dead lead resurrection"
  ],
  "1.6": [
    "Signal Classification System:",
    "Differentiate:",
    "Response",
    "Interest",
    "Commitment",
    "Quality Scoring:",
    "How strong is this contact?",
    "Score:",
    "Persona quality",
    "Problem signal",
    "Intent signal",
    "Early Disqualification Logic:",
    "When should we walk away?",
    "False Positive Detection:",
    "Looks good but isn’t:",
    "Polite replies",
    "Information seekers",
    "Non-buying stakeholders",
    "Inspection Questions:",
    "Manager deal review:",
    "What evidence says this is real?",
    "What makes this qualified?"
  ],
  "2.1": [
    "Interest Signal Taxonomy:",
    "Differentiate:",
    "Curiosity signals",
    "Pain signals",
    "Buying signals",
    "Social/polite signals",
    "Signal Strength Scoring:",
    "How strong is the signal?",
    "Examples:",
    "“Interesting…” → weak",
    "“We’re dealing with that now” → strong",
    "“Can we explore this deeper?” → very strong",
    "Can become a scoring framework.",
    "False Positive Detection:",
    "Looks like interest but isn’t:",
    "Nice person syndrome",
    "Research-only prospects",
    "Tire-kickers",
    "Competitor intelligence gathering",
    "Timing Interpretation:",
    "Interest now or later?",
    "Signals can indicate:",
    "Immediate opportunity",
    "Future nurture",
    "Low-probability distraction",
    "Inspection Layer:",
    "Manager asks:",
    "What evidence shows this is genuine interest?",
    "What makes you believe this is advancing?",
    "Treating politeness as progress",
    "Advancing stage without evidence",
    "Confusing activity with momentum"
  ],
  "2.2": [
    "Curiosity Architecture:",
    "How do you create:",
    "Tension",
    "Gap",
    "“Tell me more”",
    "Insight-Based Hooks:",
    "Train reps to use:",
    "Contrarian insights",
    "Industry observations",
    "Hidden-risk framing",
    "Tension Without Fearmongering:",
    "Create urgency",
    "without sounding manipulative.",
    "Problem Escalation Moves:",
    "Escalate the problem from:",
    "operational annoyance",
    "to",
    "strategic concern",
    "Dumping value props too early",
    "Over-educating",
    "Making problem sound too abstract"
  ],
  "2.3": [
    "Agenda Control:",
    "Set clearly:",
    "Why we’re talking",
    "What this call is for",
    "What good next step looks like",
    "Tone Control:",
    "How to sound:",
    "consultative",
    "direct",
    "peer-level",
    "Buyer Expectation Setting:",
    "Prevent wandering calls.",
    "Set expectations for:",
    "what will be covered",
    "what won’t",
    "Control Without Dominating:",
    "Lead the conversation",
    "without feeling controlling.",
    "Letting buyer ramble aimlessly",
    "No structure",
    "Losing conversation ownership"
  ],
  "2.4": [
    "Relevance Checks:",
    "Do they actually have the problem?",
    "Ownership Checks:",
    "Can they influence anything?",
    "Urgency Checks:",
    "Why should this matter now?",
    "Early Fit Testing:",
    "Can this ever become a deal?",
    "Progressive Qualification:",
    "Don’t interrogate.",
    "Layer questions naturally.",
    "Doing discovery too early here",
    "Over-qualifying too aggressively",
    "Not qualifying at all"
  ],
  "2.5": [
    "Earning the Right to Go Deeper:",
    "Discovery Positioning:",
    "How you frame next meeting:",
    "Bad:",
    "“Let’s do a demo.”",
    "Better:",
    "“Let’s understand whether this is worth solving.”",
    "Commitment Capture:",
    "Move from interest",
    "to time + intent commitment.",
    "Discovery Pre-Wiring:",
    "Set expectations before discovery call.",
    "Rushing to demo",
    "Weak handoff to discovery",
    "No explicit commitment"
  ],
  "3.1": [
    "Can become a full methodology.",
    "Problem Structure Mapping:",
    "Map:",
    "Symptoms",
    "Root causes",
    "Dependencies",
    "Failure points",
    "Not:",
    "“What challenges do you have?”",
    "Surface vs Root Problem Detection:",
    "Example:",
    "Buyer says:",
    "“Our team is slow.”",
    "Surface.",
    "Real issue may be:",
    "Broken process",
    "Bad handoffs",
    "Lack of visibility",
    "Problem Severity Analysis:",
    "How painful is it?",
    "Minor inconvenience",
    "Persistent drag",
    "Business risk",
    "Problem Frequency Analysis:",
    "One-off issue?",
    "Recurring?",
    "Systemic?",
    "Problem Ownership Mapping:",
    "Who owns this pain?",
    "Accepting first answer at face value",
    "Staying at symptom level",
    "No root-cause probing"
  ],
  "3.2": [
    "Business Impact:",
    "Quantify:",
    "Cost",
    "Delay",
    "Lost revenue",
    "Risk exposure",
    "Personal Impact:",
    "Very overlooked.",
    "How problem affects buyer:",
    "Stress",
    "Reputation",
    "Career pressure",
    "Cost of Inaction Modeling:",
    "What happens if nothing changes?",
    "Impact Prioritization:",
    "Which consequences matter most internally?",
    "Not all pain matters equally.",
    "Quantification Techniques:",
    "How to estimate impact when buyer doesn’t know.",
    "Advanced skill.",
    "Leaving pain qualitative only",
    "No cost-of-inaction discussion",
    "Assuming buyer sees urgency"
  ],
  "3.3": [
    "Existing Solution Mapping:",
    "What are they doing today?",
    "Processes",
    "Tools",
    "Workarounds",
    "Satisfaction Analysis:",
    "Are they unhappy enough to change?",
    "Gap Identification:",
    "Where current approach breaks.",
    "Switching Friction Analysis:",
    "What makes change hard?",
    "Competitive Entrenchment:",
    "If another vendor exists:",
    "How sticky are they?",
    "Why might they leave?",
    "Ignoring status quo strength",
    "Assuming dissatisfaction",
    "Not understanding switching risk"
  ],
  "3.4": [
    "Trigger Event Identification:",
    "Why now?",
    "Examples:",
    "Growth",
    "Compliance change",
    "Internal pressure",
    "Failed initiative",
    "Urgency Testing:",
    "Real urgency or artificial?",
    "Competing Priority Analysis:",
    "What else may outrank this?",
    "Time Horizon Mapping:",
    "This quarter?",
    "Next year?",
    "Trigger Creation Moves:",
    "Advanced:",
    "How to help buyer see urgency where weak.",
    "No “why now” clarity",
    "Mistaking interest for urgency",
    "Ignoring competing priorities"
  ],
  "3.5": [
    "Initial Stakeholder Identification:",
    "Who touches decision?",
    "Influence Mapping:",
    "Who influences even if not decision-maker?",
    "Hidden Stakeholder Detection:",
    "The people not named initially.",
    "Often deal killers.",
    "Political Mapping:",
    "Who may resist?",
    "Access Strategy:",
    "How do we expand beyond single-thread?",
    "Single-thread dependence",
    "Ignoring blockers",
    "No political awareness"
  ],
  "3.6": [
    "Budget Signals:",
    "Explicit or implied?",
    "Authority Signals:",
    "Who can decide?",
    "Timeline Signals:",
    "Real or aspirational?",
    "Deal Fit Qualification:",
    "Should we even pursue?",
    "Elite teams qualify out.",
    "Risk Scoring:",
    "How risky is this opportunity?",
    "Can become inspection model.",
    "Skipping uncomfortable questions",
    "Forcing deal despite weak fit",
    "Qualifying emotionally, not objectively"
  ],
  "3.7": [
    "This is advanced.",
    "Reframing Mechanics:",
    "Help buyer see problem more clearly.",
    "Not manipulation.",
    "Clarity.",
    "Elevating Problem Importance:",
    "Operational issue → strategic issue",
    "Challenging Buyer Assumptions:",
    "Respectfully.",
    "Insight-Led Repositioning:",
    "“You may be looking at symptom, not root issue.”",
    "Co-Creation of Problem Definition:",
    "Best discovery outcome:",
    "Buyer says:",
    "“Yes — that’s exactly the issue.”",
    "That’s alignment.",
    "Staying purely reactive",
    "Never challenging assumptions",
    "Making reframe feel argumentative"
  ],
  "4.1": [
    "Use-Case Mapping:",
    "Map the solution to:",
    "Their workflows",
    "Their problems",
    "Their environment",
    "No generic tours.",
    "Demo Personalization Architecture:",
    "Show only:",
    "Must-show",
    "Nice-to-show",
    "Never-show (distraction)",
    "Problem-to-Capability Linking:",
    "Every capability shown must answer:",
    "“So what?”",
    "Sequencing the Story:",
    "Show in buyer logic order, not product architecture order.",
    "Very important.",
    "Demo Control Mechanics:",
    "How to guide without rushing.",
    "Generic demo",
    "Showing too much",
    "Feature dumping",
    "Demo not tied to discovery"
  ],
  "4.2": [
    "Outcome Translation:",
    "Feature → capability → business outcome",
    "Not:",
    "“We have automation.”",
    "But:",
    "“This removes manual review delays.”",
    "Relevance Prioritization:",
    "Not every feature matters.",
    "Train signal discipline.",
    "Value Layering:",
    "Map value at multiple levels:",
    "User value",
    "Team value",
    "Executive value",
    "Enterprise alignment.",
    "Problem Coverage Analysis:",
    "Did solution address:",
    "Core pain",
    "Secondary pain",
    "Risks",
    "Gap Acknowledgment:",
    "If solution doesn’t solve something:",
    "Say it.",
    "Builds trust.",
    "Assuming buyer connects dots",
    "Feature obsession",
    "Overpromising fit"
  ],
  "4.3": [
    "Early Concern Extraction:",
    "Pull resistance out now.",
    "Hidden Skepticism Detection:",
    "Buyer says “looks good” but hesitates.",
    "Learn to detect.",
    "Objection Pattern Mapping:",
    "By stakeholder type:",
    "Finance concerns",
    "Technical concerns",
    "Adoption concerns",
    "Risk-Normalization Language:",
    "Normalize concerns early.",
    "Advanced move.",
    "Pre-Emptive Neutralization:",
    "Address likely objections before asked.",
    "Elite behavior.",
    "Assuming no objections because none voiced",
    "Waiting until procurement for concerns",
    "Defending too early"
  ],
  "4.4": [
    "This is often weak.",
    "Can become a huge module.",
    "Value Narrative Construction:",
    "Tell the “before → after” story.",
    "Tangible vs Strategic Value:",
    "Both matter.",
    "Examples:",
    "Efficiency savings",
    "Risk reduction",
    "Strategic upside",
    "Value Quantification:",
    "Move from “better” to measurable.",
    "Comparative Value Framing:",
    "Anchor against:",
    "Doing nothing",
    "Current approach",
    "Alternatives",
    "Buyer-Specific Value Language:",
    "Use THEIR words from discovery.",
    "Critical alignment move.",
    "Speaking in generic value claims",
    "Unquantified impact",
    "Talking vendor language, not buyer language"
  ],
  "4.5": [
    "Confirmation Mechanics:",
    "Don’t assume.",
    "Ask explicitly:",
    "Does this solve what we discussed?",
    "Confidence Testing:",
    "How confident are they really?",
    "Different from liking it.",
    "Fit Validation Questions:",
    "Advanced questions:",
    "“What concerns remain?”",
    "“What feels unclear?”",
    "Readiness Testing:",
    "Are they ready to take this internally?",
    "Misalignment Detection:",
    "Catch:",
    "Partial agreement",
    "Superficial agreement",
    "Hidden doubt",
    "No confirmation checkpoint",
    "Mistaking enthusiasm for conviction",
    "Moving forward with unresolved doubt"
  ],
  "5.1": [
    "Champion Definition Framework:",
    "Differentiate:",
    "Friendly contact",
    "Interested user",
    "Real champion",
    "Not the same.",
    "A champion has:",
    "Motivation",
    "Influence",
    "Willingness to push",
    "All 3.",
    "Champion Strength Assessment:",
    "How strong is the champion?",
    "Assess:",
    "Political capital",
    "Internal credibility",
    "Access upward",
    "Persistence",
    "Can become scoring model.",
    "Motivation Mapping:",
    "Why would they push this?",
    "Career gain?",
    "Problem ownership?",
    "Risk reduction?",
    "Must know.",
    "Champion vs Coach vs Mobilizer:",
    "Advanced distinction.",
    "Some help you navigate.",
    "Some advocate.",
    "Some decide.",
    "Different roles.",
    "Weak Champion Detection:",
    "Signals:",
    "Likes you, won’t push",
    "Interested, won’t introduce others",
    "Says “I’ll socialize internally” but no action",
    "Danger.",
    "Assuming friendly = champion",
    "No champion strength test",
    "Building deal on weak internal sponsor"
  ],
  "5.2": [
    "Internal Story Architecture:",
    "Equip champion to explain:",
    "Problem",
    "Impact",
    "Why change",
    "Why your solution",
    "Why now",
    "Complete narrative.",
    "Message Compression:",
    "Can they explain this in 60 seconds internally?",
    "Stakeholder-Specific Internal Story:",
    "Different narrative for:",
    "Boss",
    "Finance",
    "Tech",
    "Leadership",
    "One story does not fit all.",
    "Narrative Stress Testing:",
    "Ask:",
    "“If leadership pushes back on X, how would this be positioned?”",
    "Train before real test.",
    "Internal Presentation Coaching:",
    "Sometimes you coach them on how to present internally.",
    "Leaving buyer to “figure out how to pitch it”",
    "Complex messaging",
    "No internal story support"
  ],
  "5.3": [
    "Asset Strategy:",
    "What assets exist for:",
    "Champion support",
    "Executive review",
    "Finance review",
    "Technical review",
    "Asset Design Principles:",
    "Should be:",
    "Forwardable",
    "Short",
    "Defensible",
    "Not giant decks.",
    "Asset Sequencing:",
    "Which asset when?",
    "Timing matters.",
    "Asset Customization:",
    "Generic collateral often kills momentum.",
    "Customization may be required.",
    "Internal Sharing Risk Management:",
    "How assets can be misused or misunderstood.",
    "Often overlooked.",
    "Sending generic deck",
    "Sending too much",
    "No internal-use material"
  ],
  "5.4": [
    "Decision Process Mapping:",
    "Understand:",
    "Who approves",
    "In what order",
    "Under what criteria",
    "Formal vs Informal Decision Paths:",
    "Very important.",
    "Deals often decided before formal approval.",
    "Approval Path Risk Mapping:",
    "Where can it break?",
    "Finance?",
    "Security?",
    "Leadership?",
    "Map it.",
    "Internal Timeline Mapping:",
    "How long does process really take?",
    "Not “we’ll move fast.”",
    "Reality.",
    "Decision Path Influence Strategy:",
    "How do we improve odds at each step?",
    "Assuming linear process",
    "Ignoring hidden approval layers",
    "No process visibility"
  ],
  "5.5": [
    "Can still expand further.",
    "Objection Forecasting:",
    "Predict objections by stakeholder.",
    "Objection Battle Cards:",
    "Prepare responses champion can use.",
    "Silent Resistance Detection:",
    "What concerns may never be voiced?",
    "Political Objection Management:",
    "Some objections are not rational.",
    "They are territorial.",
    "Risk Reduction Narrative:",
    "How to make “yes” feel safer.",
    "Reactive objection handling",
    "Not equipping champion",
    "Ignoring internal political resistance"
  ],
  "6.1": [
    "Can become a major discipline.",
    "Stakeholder Taxonomy:",
    "Map:",
    "Economic buyer",
    "Technical evaluator",
    "Functional owner",
    "End user",
    "Procurement",
    "Blockers",
    "Each plays different game.",
    "Visible vs Hidden Stakeholders:",
    "The people named initially",
    "are often not all the people involved.",
    "Power vs Influence Mapping:",
    "Some approve.",
    "Some shape approvals.",
    "Different.",
    "Stakeholder Priority Ranking:",
    "Who matters most?",
    "Not equal weighting.",
    "Missing Stakeholder Detection:",
    "Who is absent that should worry you?",
    "Believing stakeholder map is complete too early",
    "Ignoring hidden influencers",
    "Treating all stakeholders equally"
  ],
  "6.2": [
    "Message Differentiation Strategy:",
    "Different stakeholders need different cases.",
    "Example:",
    "CFO hears ROI/risk",
    "CTO hears integration/security",
    "User hears usability",
    "Same product. Different story.",
    "Incentive Alignment Messaging:",
    "Map message to what each person cares about.",
    "Very important.",
    "Language Translation:",
    "Avoid using same language across personas.",
    "Buyer alignment 101.",
    "Objection-Specific Messaging:",
    "Different personas raise different concerns.",
    "Prepare for each.",
    "Message Consistency Control:",
    "Messages can differ…",
    "but cannot contradict.",
    "Same pitch for everyone",
    "Misreading stakeholder priorities",
    "Inconsistent narratives"
  ],
  "6.3": [
    "Stakeholder Risk Mapping:",
    "For each stakeholder:",
    "What worries them?",
    "Cost risk",
    "Security risk",
    "Operational risk",
    "Career risk",
    "Resistance Pattern Detection:",
    "Who may resist and why?",
    "Sometimes resistance is political.",
    "Not logical.",
    "Risk Reduction Strategies:",
    "How to reduce perceived downside.",
    "Concern Isolation:",
    "Which risks are real blockers",
    "vs surface objections?",
    "Escalation Prevention:",
    "How to prevent small concerns becoming deal-threatening.",
    "Treating concerns lightly",
    "Responding only when escalated",
    "Ignoring political resistance"
  ],
  "6.4": [
    "Consensus Definition:",
    "Not:",
    "Everyone likes solution.",
    "But:",
    "Key stakeholders can move forward together.",
    "Different.",
    "Consensus Gap Detection:",
    "Who is aligned?",
    "Who is not?",
    "Consensus Sequencing:",
    "Order matters.",
    "Sometimes you win:",
    "Technical first",
    "Then executive",
    "Sometimes reverse.",
    "Conflict Resolution:",
    "What if stakeholders disagree?",
    "Internal Coalition Strengthening:",
    "How to help supporters align internally.",
    "Assuming silence means consensus",
    "Advancing with one stakeholder misaligned",
    "Ignoring stakeholder conflict"
  ],
  "7.1": [
    "Scope Architecture:",
    "Define:",
    "What is included",
    "What is excluded",
    "What is being tested",
    "Without this:",
    "Chaos.",
    "Use Case Selection:",
    "Which use cases go into pilot?",
    "Choose ones that:",
    "Can show value",
    "Are feasible",
    "Matter politically",
    "Strategic decision.",
    "Scope Size Calibration:",
    "Too small:",
    "No meaningful proof",
    "Too large:",
    "Execution risk explodes",
    "Important balancing act.",
    "Resource Definition:",
    "Who does what?",
    "Buyer side",
    "Seller side",
    "Must be explicit.",
    "Scope Drift Prevention:",
    "How to stop pilot expanding endlessly.",
    "Undefined scope",
    "Pilot becoming broad exploration",
    "No ownership clarity"
  ],
  "7.2": [
    "Success Criteria Architecture:",
    "What does “pilot success” actually mean?",
    "Must be defined before start.",
    "Not after.",
    "Quantitative Metrics:",
    "Examples:",
    "Time reduction",
    "Error reduction",
    "ROI indicator",
    "Qualitative Metrics:",
    "Examples:",
    "User confidence",
    "Workflow improvement",
    "Stakeholder satisfaction",
    "Stakeholder-Specific Success Measures:",
    "Finance may define success differently than users.",
    "Very important.",
    "Failure Threshold Definition:",
    "What would count as pilot failure?",
    "Almost never discussed.",
    "Should be.",
    "No agreed success metrics",
    "Vague “we’ll see how it goes”",
    "Measuring after the fact"
  ],
  "7.3": [
    "Often underestimated.",
    "Pilot Management Structure:",
    "How pilot is managed:",
    "Cadence",
    "Ownership",
    "Escalation path",
    "High-Touch Support Strategy:",
    "Pilots often need disproportionate support.",
    "Done right:",
    "Wins deals.",
    "Adoption Enablement:",
    "Support actual usage.",
    "Not just setup.",
    "Friction Removal Process:",
    "How issues are handled quickly.",
    "Stakeholder Communication During Pilot:",
    "Keep key people informed.",
    "Don’t let silence define narrative.",
    "“Set it and forget it” pilot",
    "Poor support",
    "Allowing usage issues to define perception"
  ],
  "7.4": [
    "Progress Review Cadence:",
    "Weekly?",
    "Biweekly?",
    "Signal Monitoring:",
    "Track:",
    "Positive indicators",
    "Warning indicators",
    "Early.",
    "Mid-Pilot Course Correction:",
    "How to fix issues before failure.",
    "Win Narration During Pilot:",
    "Don’t wait until end to communicate wins.",
    "Stakeholder Visibility Management:",
    "Ensure decision-makers see progress.",
    "No tracking rhythm",
    "Surprises discovered late",
    "Value happening but not being noticed"
  ],
  "7.5": [
    "Outcome Review Structure:",
    "Formal review:",
    "What happened",
    "What was proven",
    "What remains",
    "Results Interpretation:",
    "Did pilot prove enough?",
    "Not always obvious.",
    "Gap Analysis:",
    "What concerns remain after pilot?",
    "Proof-to-Commercial Transition:",
    "How to move from proof",
    "to buying motion.",
    "Often mishandled.",
    "Failure Diagnosis:",
    "If pilot underperformed:",
    "Why?",
    "Salvageable?",
    "Disqualify?",
    "No structured outcome review",
    "Assuming successful pilot means automatic deal",
    "No transition plan after proof"
  ],
  "8.1": [
    "Value Anchor Construction:",
    "Anchor price against:",
    "Cost of problem",
    "Cost of inaction",
    "Economic upside",
    "Not against arbitrary number.",
    "Economic Framing Strategy:",
    "Position spend as:",
    "Investment",
    "Risk reduction",
    "Payback decision",
    "Not expense.",
    "Anchor Timing:",
    "When do you establish value anchor?",
    "Too late = weak pricing power.",
    "Comparative Anchoring:",
    "Anchor against:",
    "Current cost",
    "Alternatives",
    "Doing nothing",
    "Powerful.",
    "Anchor Defense:",
    "How to hold anchor under pressure.",
    "Leading with price before value anchor",
    "Discounting before resistance understood",
    "Letting buyer anchor value downward"
  ],
  "8.2": [
    "Much deeper than “quote.”",
    "Packaging Strategy:",
    "Offer structure options:",
    "Tiers",
    "Scope bundles",
    "Commercial options",
    "Price Architecture:",
    "How pricing model aligns to buyer logic.",
    "Very important.",
    "Offer Configuration:",
    "What should be included or excluded?",
    "A deal design skill.",
    "Flexibility Boundaries:",
    "What can move?",
    "What cannot?",
    "Reps must know.",
    "Commercial Simplicity:",
    "Complex pricing can kill deals.",
    "Often overlooked.",
    "Random pricing concessions",
    "Overcomplicated packaging",
    "No structure behind offer"
  ],
  "8.3": [
    "Budget Reality Testing:",
    "Validate whether there is:",
    "Allocated budget?",
    "Potential budget?",
    "No funding path?",
    "Different deals.",
    "Funding Path Mapping:",
    "How would this get funded?",
    "Approval Mechanics:",
    "Who approves spend?",
    "Budget Timing Analysis:",
    "Current cycle?",
    "Next cycle?",
    "Economic Sponsor Validation:",
    "Is there someone who can defend spend?",
    "Assuming budget exists",
    "Not understanding funding path",
    "Discovering budget issue too late"
  ],
  "8.4": [
    "Negotiation Strategy Design:",
    "Negotiation strategy:",
    "Hold? Trade? Concede conditionally?",
    "Must be deliberate.",
    "Concession Discipline:",
    "If something is given—",
    "something is gained.",
    "Always.",
    "Pushback Diagnosis:",
    "“Too expensive” means what?",
    "No budget?",
    "Weak value?",
    "Negotiation tactic?",
    "Different responses.",
    "Trade Mechanics:",
    "Exchange:",
    "Scope",
    "Terms",
    "Timing",
    "Volume",
    "Not pure discounting.",
    "Negotiation Control:",
    "How to avoid buyer controlling entire commercial dynamic.",
    "Immediate discounting",
    "Unconditional concessions",
    "Arguing price instead of defending value",
    "Mistaking negotiation tactic for true objection"
  ],
  "9.1": [
    "Can become a major module.",
    "Onboarding Requirements Mapping:",
    "Understand upfront:",
    "Required forms",
    "Vendor registration steps",
    "Compliance documents",
    "Documentation Readiness:",
    "Prepare:",
    "Tax docs",
    "Insurance docs",
    "Company documentation",
    "Buyer Process Variation Mapping:",
    "Every buyer’s process differs.",
    "Must adapt.",
    "Timeline Risk Assessment:",
    "How long does onboarding really take?",
    "Pre-Emptive Preparation:",
    "Can some steps be started early?",
    "Discovering requirements late",
    "Missing documentation",
    "Treating onboarding as trivial"
  ],
  "9.2": [
    "Contract Structure Understanding:",
    "Know:",
    "Standard terms",
    "Risk points",
    "Negotiable points",
    "Reps should not be blind.",
    "Clause Risk Mapping:",
    "Which clauses commonly create friction?",
    "Examples:",
    "Liability",
    "Indemnity",
    "Termination",
    "Data usage",
    "Negotiation Path Design:",
    "How legal escalations get resolved.",
    "Redline Management:",
    "How to manage back-and-forth efficiently.",
    "Business Impact of Terms:",
    "When legal terms affect commercial reality.",
    "Treating legal as someone else’s problem",
    "Slow redline response",
    "Ignoring business implications of terms"
  ],
  "9.3": [
    "Security Evaluation Mapping:",
    "Likely requirements:",
    "Security review",
    "Data review",
    "Architecture questions",
    "Risk Concern Forecasting:",
    "What security may object to.",
    "Pre-think it.",
    "Technical Validation Support:",
    "How to support security review.",
    "Security Objection Handling:",
    "Security Delay Prevention:",
    "How to avoid security becoming black hole.",
    "Security engaged too late",
    "Treating security review casually",
    "Slow response to technical concerns"
  ],
  "9.4": [
    "Much deeper than “finish terms.”",
    "Final Commercial Integrity Check:",
    "Did concessions damage deal quality?",
    "Important.",
    "End-Stage Pressure Handling:",
    "Buyers sometimes push hardest here.",
    "Need discipline.",
    "Trade Closure Strategy:",
    "What gets finalized",
    "and under what conditions.",
    "Final Risk Review:",
    "Any unresolved issue left?",
    "Must inspect.",
    "Commitment Lock-In:",
    "What makes signature actually likely?",
    "Giving away too much at end",
    "Rushing through unresolved risk",
    "Assuming signature is automatic"
  ],
  "10.1": [
    "Signature Readiness Validation:",
    "Before sending for signature:",
    "Is everything actually aligned?",
    "Terms resolved",
    "Stakeholders aligned",
    "Internal approvals complete",
    "Signature Path Mapping:",
    "Who signs?",
    "How?",
    "In what sequence?",
    "Final Commitment Confirmation:",
    "Before signature:",
    "Reconfirm mutual commitment.",
    "Signature Risk Detection:",
    "What could still derail before signing?",
    "Must inspect.",
    "Close Timing Management:",
    "Timing of close can matter.",
    "Quarter-end pressure, approvals timing, etc.",
    "Sending agreement before alignment is real",
    "Assuming signature is inevitable",
    "Ignoring final-stage risks"
  ],
  "10.2": [
    "Often under-owned by sales.",
    "Transition Planning:",
    "Plan the handoff from:",
    "From sales",
    "To onboarding / delivery",
    "Implementation Scope Alignment:",
    "What happens first?",
    "What does buyer expect?",
    "Ownership Mapping:",
    "Who owns what post-close?",
    "Early Success Milestone Design:",
    "What does success in first 30/60/90 days look like?",
    "Powerful.",
    "Implementation Risk Prevention:",
    "Prevent surprises after signing.",
    "Weak handoff",
    "Misaligned implementation expectations",
    "No ownership clarity"
  ],
  "10.3": [
    "Post-Signature Stakeholder Continuity:",
    "Do relationships continue with right people?",
    "Role Alignment:",
    "Who does what internally?",
    "Commitment Reinforcement:",
    "Re-anchor:",
    "Why they bought.",
    "Important psychologically.",
    "Change Readiness Assessment:",
    "Is buyer organization ready for what comes next?",
    "Often overlooked.",
    "Escalation Path Definition:",
    "If issues arise, what happens?",
    "Stakeholders disengage after signature",
    "Roles unclear",
    "Buyer assumes different responsibilities than seller"
  ],
  "10.4": [
    "Success Criteria Confirmation:",
    "What does buyer define as success now?",
    "Outcome Tracking Plan:",
    "How will success be measured?",
    "Value Realization Planning:",
    "How promised value actually gets realized.",
    "Expansion Signal Identification:",
    "Successful close can create growth path.",
    "Churn Risk Detection:",
    "What could threaten success early?",
    "Important.",
    "No defined success plan",
    "Assuming product use = value realization",
    "No early risk detection"
  ]
} as const;
